version: 2.1

jobs:
  build:
    working_directory: ~/be-redux-react
    docker:
      - image: circleci/node:13.14-browsers

    steps:
      - checkout

      # Restore the dependency cache
      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies with NPM
          command: yarn install

      # Save the dependency cache
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # I kept this commented because it fails
      # - run: 
      #     name: Validate the style of the code
      #     command: yarn lint

      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: yarn test --collectCoverage=true
      - store_artifacts:
          path: coverage

  nightwatch:
    working_directory: ~/be-redux-react
    docker:
      - image: circleci/ruby:2.6-stretch-node-browsers-legacy
    steps:
      - checkout

      # Restore the dependency cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies with NPM
          command: yarn install

      - run:
          name: Run the Selenium server
          command: yarn run launch-selenium

      - run:
          name: Run the React server
          command: yarn run launch-react-app

      - run:
          name: Clone the BrowseEverything app.
          command: git clone -b 2.x-stable https://github.com/samvera/browse-everything.git

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "browse-everything/browse-everything.gemspec" }}

      - run:
          name: Install Gem dependencies
          command: |
            cd browse-everything
            bundle check || bundle install

      - run:
          name: Generate the server
          command: |
            cd browse-everything
            [ -e ./.internal_test_app ] || bundle exec rake engine_cart:generate

      - run:
          name: Set the Rails secret
          command: |
            cp tests/support/master.key browse-everything/.internal_test_app/config/
            cp tests/support/credentials.yml.enc browse-everything/.internal_test_app/config/

      - save_cache:
          key: v1-dependencies-{{ checksum "browse-everything/browse-everything.gemspec" }}
          paths:
            - ~/be-redux-react/browse-everything/vendor/bundle
            - ~/be-redux-react/browse-everything/.internal_test_app

      - run:
          name: Update the ENV configuration file
          command: |
            sed -i "s/RAILS_SECRET/$RAILS_SECRET/g" .env
            sed -i "s/GOOGLE_CLIENT_ID/$GOOGLE_CLIENT_ID/g" .env
            sed -i "s/GOOGLE_DEVELOPER_KEY/$GOOGLE_DEVELOPER_KEY/g" .env

      - run:
          name: Starting Rails server
          command: |
            sed -i "s/GOOGLE_API_CLIENT_ID/$GOOGLE_CLIENT_ID/g" tests/support/browse_everything_providers.yml
            sed -i "s/GOOGLE_API_CLIENT_SECRET/$GOOGLE_CLIENT_SECRET/g" tests/support/browse_everything_providers.yml
            cp tests/support/browse_everything_providers.yml browse-everything/.internal_test_app

      - run:
          name: Starting Rails server
          command: |
            bundle exec rails s > rails_server.log 2>&1 &

      - run:
          name: Run the Selenium server
          command: yarn run nightwatch

      # Save the dependency cache
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  e2e:
    jobs:
      - nightwatch
