version: 2.1

jobs:
  build:
    working_directory: ~/be-redux-react
    docker:
      - image: circleci/node:12.14.0-browsers

    steps:
      - checkout

      # Restore the dependency cache
      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies with NPM
          command: yarn install

      # Save the dependency cache
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # I kept this commented because it fails
      # - run: 
      #     name: Validate the style of the code
      #     command: yarn lint

      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: yarn test --collectCoverage=true
      - store_artifacts:
          path: coverage

  react_server:
    working_directory: ~/be-redux-react
    docker:
      - image: circleci/node:12.14.0-browsers
    steps:
      - checkout

      # Restore the dependency cache
      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies with NPM
          command: yarn install

      - run:
          name: Run the Selenium server
          command: yarn run e2e

      - run:
          name: Run the React server
          command: yarn run start

      # Save the dependency cache
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  nightwatch:
    working_directory: ~/be-redux-react
    docker:
      - image: circleci/node:12.14.0-browsers
    steps:
      - checkout

      # Restore the dependency cache
      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies with NPM
          command: yarn install

      - run:
          name: Run the Selenium server
          command: yarn run launch-selenium

      - run:
          name: Run the React server
          command: yarn run react-start

      - run:
          name: Run the Selenium server
          command: yarn run nightwatch

      # Save the dependency cache
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  e2e:
    jobs:
      - nightwatch
